### ISSUE TITLE
isCustomDate not working 

### ISSUE THREAD

**Issue by DeepakCodeWaves** [iulius-ciorica/ngx-daterangepicker-bootstrap#10]
isCustomDate is not working and not giving any error , I have selected a random date 

  customizeDatess(date: Dayjs): string {
    const formattedDate = date.format('YYYY-MM-DD');
      if (formattedDate === '2024-09-15') {
      return 'background-color: green; color: white;';
    }
      return '';
  }
   <input type="text"
         ngxDaterangepickerBootstrap
         [isCustomDate]="customizeDatess.bind(this)"
         [isInvalidDate]="disablePastDatess"
         [isTooltipDate]="addHolidayTooltipss"
         class="form-control" />

**Comment by adora-tech** [comment]
Hello,

See if this help you,
https://fetrarij.github.io/ngx-daterangepicker-material/single-datepicker

Thank you,
Iulius

**Comment by DeepakCodeWaves** [comment]
Thanks

**Comment by DeepakCodeWaves** [comment]
Hi Iulius,

Thank you for your reply. I will check out the link you provided and let
you know if I have any further questions.

Thanks,
Deepak Verma
