### ISSUE TITLE
bootstrap 4

### ISSUE THREAD

**Issue by kodeine** [iulius-ciorica/ngx-daterangepicker-bootstrap#2]
Hello,

do we still have a tag for bootstrap 4? but angular 13+ ? The problem i'm facing is that my entire template is bootstrap 4 and if i upgrade that to 5 it will be a massive change. 

Can we support bootstrap 4 on this repo or is it possible to make it as a web component (angular element) so it can be used as is within my application?

**Comment by iulius-ciorica** [comment]
Hello,

I do not provide support for older versions, sorry.

Maybe it is useful for your case:

https://github.com/evansmwendwa/ng2-daterangepicker
https://stackblitz.com/edit/ng2-daterangepicker-txpnjb

or you can make a fork and modify it for your case.

Thank you,

**Comment by kodeine** [comment]
Thank you
