### ISSUE TITLE
Angular 17

### ISSUE THREAD

**Issue by jbaan** [iulius-ciorica/ngx-daterangepicker-bootstrap#3]
During npm install of this library in Angular 17 project an error is there that this libray is for Angular 16. However library is working fine in Angular 17. Can you upgrade it to Angular 17?

**Comment by iulius-ciorica** [comment]
I've been a bit busy.
Yes, I will do an update these days ...

Thank you,

**Comment by iulius-ciorica** [comment]
Version 17.5.1 has been released.
