### ISSUE TITLE
minDate functionality for daterangepicker

### ISSUE THREAD

**Issue by erdenerunl** [iulius-ciorica/ngx-daterangepicker-bootstrap#4]
Hi, 
First, thank you for your efforts. I am currently using this project, but I have an issue using the minDate feature. Is this an internal bug or something else? 

The minDate parameter is not working. I already tried to use dayjs(), 0, and 'today'. My aim is preventing the selection of any date before current date(today). 

Angular v16.2.12,
ngx-daterangepicker-bootstrap 16.5.0

**Comment by iulius-ciorica** [comment]
Hello,

See if this helps you:
https://github.com/fetrarij/ngx-daterangepicker-material/issues/521

Thank you,
