### ISSUE TITLE
apply button is disabled when timePicker value changes

### ISSUE THREAD

**Issue by janzimmermann1** [iulius-ciorica/ngx-daterangepicker-bootstrap#8]
When a timePicker value changes for example the startTime from 2AM to 3AM the apply button is still disabled.
This bug is also visible on the stackblitz demo: https://stackblitz.com/edit/ngx-daterangepicker-bootstrap-18-5-0?file=package.json

To have the time range changes first the date has to be selected again and then the time can be changed.

**Comment by iulius-ciorica** [comment]
Hello,

I know about this behavior, I will consider it in the next major v19 release.

Thank you.

**Comment by zioerjens** [comment]
Hello,

Thanks for maintaining the project and providing one of the few date-time range pickers out there.

Would it be possible to release it before v19, or generally soon? It's making the functionality of picking a time range almost unusable.

Best regards

**Comment by iulius-ciorica** [comment]
@janzimmermann1 @zioerjens 

This issue has been fixed and released as part of [v18.5.1](https://github.com/iulius-ciorica/ngx-daterangepicker-bootstrap/releases/tag/v18.5.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
