### ISSUE TITLE
Crash in ngOnDestroy: "Failed to execute 'removeChild' on 'Node'".

### ISSUE THREAD

**Issue by mr0j** [iulius-ciorica/ngx-daterangepicker-bootstrap#9]
Hello,

In my case picker can be shown and removed dynamically. When the picker is released, there is crash in ngOnDestroy:

> ERROR NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> at NgxDaterangepickerBootstrapDirective.ngOnDestroy (ngx-daterangepicker-bootstrap.mjs:1675:27)

In this case the picker is not direct child of document.body, that is the reason of exception.
Problem is in this line:
`if (selector !== null) document.body.removeChild(selector);`

You can change it to something like this to fix this problem:
`if (selector !== null) selector.remove();`

Could you please change ngOnDestroy() method of NgxDaterangepickerBootstrapDirective and if possible do it in version 17?

**Comment by iulius-ciorica** [comment]
Hello,

I do not provide support for older versions.

Here you can find a simple example, which uses angular 17 and works correctly.
`https://stackblitz.com/edit/ngx-daterangepicker-bootstrap-17-5-0-zwy1u1`

I also use ngx-daterangepicker-bootstrap, inside/with ngx-formly and there are no issues.
`https://github.com/ngx-formly/ngx-formly`

For your particular/special case, you can copy the sources and then apply the desired changes.

You can also provide a simple stackblitz example where the problem can be reproduced, if you want, but there is no guarantee that your request here will be considered.

Thank you,
Iulius
